### ISSUE TITLE
Release version 1.3.0 on Maven Central

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-community-hub/zeebe-worker-java-testutils#54] opened 2022-03-07 16:28 UTC
Version `1.3.0` is published on GitHub but not on Maven Central: https://search.maven.org/artifact/io.zeebe/zeebe-worker-java-testutils

**Comment by berndruecker** [comment] 2022-03-09 11:24
Did you click on "close" for the repo?

**Comment by berndruecker** [comment] 2022-03-09 11:28
I closed it now: 
![grafik](https://user-images.githubusercontent.com/1217596/157433026-9d88e261-5886-415e-9f82-a0b2022b441f.png)

**Comment by berndruecker** [comment] 2022-03-09 11:34
Closed properly, released it now (hope that was intended)

**Comment by pihme** [comment] 2022-03-09 11:37
Ah, I wasn't aware of that.

**Closed by pihme** 2022-03-09 11:37 UTC
Labels: waiting-for-camunda
